spring:
  application:
    name: helloservice
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.cert
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/300kks?schema=helloservice
    username: postgres
    password: postgres

flyway.url: jdbc:postgresql://localhost:5432/300kks?currentSchema=helloservice
flyway.user: postgres
flyway.password: postgres

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system:14268/api/traces
